# Generated by Django 4.0.1 on 2022-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Invoice_Number', models.IntegerField(blank=True, null=True)),
                ('Invoice_Date', models.DateField(auto_now_add=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer Name')),
                ('Address', models.TextField(blank=True, null=True)),
                ('Phone_Number', models.IntegerField(verbose_name='Phone Number')),
                ('Product_1', models.CharField(blank=True, max_length=100, null=True)),
                ('P1_Quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('P1_UnitPrice', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('P1_TotalPrice', models.FloatField(default=0, editable=False)),
                ('Product_2', models.CharField(blank=True, max_length=100, null=True)),
                ('P2_Quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('P2_UnitPrice', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('P2_TotalPrice', models.FloatField(default=0, editable=False)),
                ('Product_3', models.CharField(blank=True, max_length=100, null=True)),
                ('P3_Quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('P3_UnitPrice', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price')),
                ('P3_TotalPrice', models.FloatField(default=0, editable=False)),
                ('Total', models.FloatField(default=0, editable=False)),
                ('paid', models.BooleanField(default=False)),
                ('InvoiceType', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Business', 'Business')], default='', max_length=100, null=True)),
            ],
        ),
    ]
